import { IsString, IsNumber, IsEnum } from 'class-validator';

export class CreateAssetDto {
  @IsString()
  number: string;

  @IsString()
  name: string;

  @IsString()
  description: string;

  @IsString()
  sku: string;

  @IsEnum(['Fair', 'Good', 'Very Good'])
  condition: 'Fair' | 'Good' | 'Very Good';

  @IsNumber()
  qty_in: number;

  @IsNumber()
  qty_out: number;

  @IsNumber()
  unit_price: number;

  // ❌ Removed because it's generated by MySQL:
  // total_price: number;

  @IsNumber()
  threshold: number;
}
